### ISSUE TITLE
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by gudukuaile** [sun1638650145/bunnyburrow-weread#1]
File "E:\software\anaconda\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\software\anaconda\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\mywork\python\小项目\微信读书\bunnyburrow-weread\weread\core\download.py", line 208, in download
    book_metadata = await page.Jeval('#app', '''(elm) => {
  File "E:\software\anaconda\lib\site-packages\pyppeteer\page.py", line 393, in querySelectorEval
    return await frame.querySelectorEval(selector, pageFunction, *args)
  File "E:\software\anaconda\lib\site-packages\pyppeteer\frame_manager.py", line 350, in querySelectorEval
    return await document.querySelectorEval(selector, pageFunction, *args)
  File "E:\software\anaconda\lib\site-packages\pyppeteer\element_handle.py", line 413, in querySelectorEval
    result = await self.executionContext.evaluate(
  File "E:\software\anaconda\lib\site-packages\pyppeteer\execution_context.py", line 53, in evaluate
    handle = await self.evaluateHandle(
  File "E:\software\anaconda\lib\site-packages\pyppeteer\execution_context.py", line 112, in evaluateHandle
    raise ElementHandleError('Evaluation failed: {}'.format(
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property '$store' of undefined
    at __pyppeteer_evaluation_script__:2:28
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "E:\software\anaconda\lib\site-packages\pyppeteer\launcher.py", line 153, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "E:\software\anaconda\lib\asyncio\base_events.py", line 622, in run_until_complete
    self._check_closed()
  File "E:\software\anaconda\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

在download函数中 book_metadata = await page.Jeval('#app', '''(elm) => {
这段代码没有获取到内容

**Comment by morning-start** [comment]
我也遇到了同样的问题

**Comment by czy20010112** [comment]
我也遇到了一样的问题，请问前几位大佬们解决了吗 或者找到平替的项目了吗

**Comment by ghost** [comment]
同问题

**Comment by HaaiSo** [comment]
同样的问题，获取不到bookmetadata
